// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sib.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class C3;
@class C3P;
@class C4P;
@class K;
@class Pair;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SibRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SibRoot : GPBRootObject
@end

#pragma mark - M2

typedef GPB_ENUM(M2_FieldNumber) {
  M2_FieldNumber_M1 = 1,
  M2_FieldNumber_M2P2 = 2,
  M2_FieldNumber_M2P3 = 3,
  M2_FieldNumber_M3P3 = 4,
  M2_FieldNumber_M4P3 = 5,
  M2_FieldNumber_K = 6,
};

typedef GPB_ENUM(M2_OneOf_OneOfCase) {
  M2_OneOf_OneOfCase_GPBUnsetOneOfCase = 0,
  M2_OneOf_OneOfCase_M1 = 1,
  M2_OneOf_OneOfCase_M2P2 = 2,
  M2_OneOf_OneOfCase_M2P3 = 3,
  M2_OneOf_OneOfCase_M3P3 = 4,
  M2_OneOf_OneOfCase_M4P3 = 5,
  M2_OneOf_OneOfCase_K = 6,
};

@interface M2 : GPBMessage

@property(nonatomic, readonly) M2_OneOf_OneOfCase oneOfOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) C3 *m1;

@property(nonatomic, readwrite, strong, null_resettable) C3 *m2P2;

@property(nonatomic, readwrite, strong, null_resettable) C3P *m2P3;

@property(nonatomic, readwrite, strong, null_resettable) C4P *m3P3;

@property(nonatomic, readwrite, strong, null_resettable) C3P *m4P3;

@property(nonatomic, readwrite, strong, null_resettable) K *k;

@end

/**
 * Clears whatever value was set for the oneof 'oneOf'.
 **/
void M2_ClearOneOfOneOfCase(M2 *message);

#pragma mark - C3

typedef GPB_ENUM(C3_FieldNumber) {
  C3_FieldNumber_C1 = 1,
  C3_FieldNumber_C2 = 2,
  C3_FieldNumber_C3 = 3,
};

@interface C3 : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *c1;

@property(nonatomic, readwrite, copy, null_resettable) NSData *c2;

@property(nonatomic, readwrite, copy, null_resettable) NSData *c3;

@end

#pragma mark - C3P

typedef GPB_ENUM(C3P_FieldNumber) {
  C3P_FieldNumber_C1 = 1,
  C3P_FieldNumber_C2 = 2,
  C3P_FieldNumber_C3 = 3,
};

@interface C3P : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *c1;

@property(nonatomic, readwrite, copy, null_resettable) NSData *c2;

@property(nonatomic, readwrite, strong, null_resettable) Pair *c3;
/** Test to see if @c c3 has been set. */
@property(nonatomic, readwrite) BOOL hasC3;

@end

#pragma mark - C4P

typedef GPB_ENUM(C4P_FieldNumber) {
  C4P_FieldNumber_C1 = 1,
  C4P_FieldNumber_C2 = 2,
  C4P_FieldNumber_C3 = 3,
  C4P_FieldNumber_C4 = 4,
};

@interface C4P : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *c1;

@property(nonatomic, readwrite, copy, null_resettable) NSData *c2;

@property(nonatomic, readwrite, copy, null_resettable) NSData *c3;

@property(nonatomic, readwrite, strong, null_resettable) Pair *c4;
/** Test to see if @c c4 has been set. */
@property(nonatomic, readwrite) BOOL hasC4;

@end

#pragma mark - K

typedef GPB_ENUM(K_FieldNumber) {
  K_FieldNumber_K1K2 = 1,
};

@interface K : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Pair *k1K2;
/** Test to see if @c k1K2 has been set. */
@property(nonatomic, readwrite) BOOL hasK1K2;

@end

#pragma mark - Pair

typedef GPB_ENUM(Pair_FieldNumber) {
  Pair_FieldNumber_First = 1,
  Pair_FieldNumber_Second = 2,
};

@interface Pair : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *first;

@property(nonatomic, readwrite, copy, null_resettable) NSData *second;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
